### ISSUE TITLE
Testrunner breaks when an SVG is used.

### ISSUE THREAD

**Issue by Primajin** [stylesuxx/generator-react-webpack-redux#39]
similar to the yeoman Logo I wanted to add my logo:

  ```javascript
const logo = require('../images/logo.svg');
```

that works perfectly fine. But when I try to run the tests:

  ```shell
ERROR in ./src/images/logo.svg
Module parse failed: /path/src/images/logo.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/path/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/path/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/path/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/path/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/path/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/path/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/path/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/path/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/path/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/path/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/path/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/path/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/path/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/path/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/path/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/path/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./src/components/SomeComponent.js 58:51-90
```

Any Idea?

**Comment by Primajin** [comment]
BTW, when I rename the Image to `logo.svg.png` the error is gone, but the image does not work in the browser anymore.

**Comment by stylesuxx** [comment]
Hmm, seems as if the test runner tries to interpret the svg. This may be related to the webpack config.
Will check it out and report back.

**Comment by Primajin** [comment]
Any Ideas how I can tell the testrunner to ignore *.svg files? Or maybe a workaround inside the component when environment is test then ignore the image?

**Comment by stylesuxx** [comment]
Alright, so I checked with the new release > 1.0.0 I do not have this problem. Seems this has been fixed in the newer version of the base generator. Maybe you could test it and report back?

**Comment by Primajin** [comment]
Sorry I was on vacation. Thanks for looking into that, I will test with the newest version and reopen if problem still persists.

**Comment by Primajin** [comment]
So upgrading was not so easily possible for me, so I will give 1.0 a try after starting a complete new Project.
- I got also the error that webpack 2 is an unmet peer dependency when trying to set it up un a complete new folder.

So anyway: After some more searching i could fix the error with the SVG by adding the filetype to:

`cfg/test.js:25`
